In [82]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.spatial import distance_matrix
from scipy.spatial.distance import pdist, squareform

from sklearn import metrics
from sklearn.metrics import jaccard_score


import nltk
from nltk.corpus import webtext
from nltk.probability import FreqDist
from nltk import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer

import matplotlib.pyplot as plt

import re
import numpy as np
import pandas as pd

corpus = []

data = pd.read_csv("Data/Articles_short2.csv", encoding='mbcs')

def scrub_words(text):
    """Basic cleaning of texts."""
    
    # remove html markup
    text=re.sub("(<.*?>)","",text)
    
    #remove non-ascii and digits
    text=re.sub("(\\W|\\d)"," ",text)
    
    #remove whitespace
    text=text.strip()
    return text


corpus = []

df = pd.DataFrame(data)
for i in range(4):
    corpus.append(scrub_words(df.iloc[i,0]))

porter_stemmer=PorterStemmer()


def my_preprocessor(text):
    
    text=text.lower() #lowercase text (done be default if don't use a custom preprocessor)
    text=re.sub("\\W"," ",text) # remove special chars
    text=re.sub("\\s+(in|the|all|for|and|on)\\s+"," _connector_ ",text) # normalize certain words
    
    # stem words
    words=re.split("\\s+",text)
    stemmed_words=[porter_stemmer.stem(word=word) for word in words]
    return ' '.join(stemmed_words)

# GENERATE WORD COUNTS FROM ARTICLES
cv = CountVectorizer(corpus, preprocessor=my_preprocessor, stop_words='english')
count_vector=cv.fit_transform(corpus).todense()

count_vector.shape

# USING SCIPY DISTANCE_MATRIX

dm = distance_matrix(count_vector,count_vector)

print(dm)

#

euclid_distance = pd.DataFrame(squareform(pdist(count_vector)), index = range(len(corpus)), columns = range(len(corpus)))

print(euclid_distance)




[[ 0.         77.08436936 16.1245155  58.83026432]
 [77.08436936  0.         84.82924024 36.53765181]
 [16.1245155  84.82924024  0.         67.04476117]
 [58.83026432 36.53765181 67.04476117  0.        ]]
           0          1          2          3
0   0.000000  77.084369  16.124515  58.830264
1  77.084369   0.000000  84.829240  36.537652
2  16.124515  84.829240   0.000000  67.044761
3  58.830264  36.537652  67.044761   0.000000


C:\Users\hugho\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass input=['KARACHI  The Sindh government has decided to bring down public transport fares by   per cent due to massive reduction in petroleum product prices by the federal government  Geo News reported Sources said reduction in fares will be applicable on public transport  rickshaw  taxi and other means of traveling Meanwhile  Karachi Transport Ittehad  KTI  has refused to abide by the government decision KTI President Irshad Bukhari said the commuters are charged the lowest fares in Karachi as compare to other parts of the country  adding that   pc vehicles run on Compressed Natural Gas  CNG   Bukhari said Karachi transporters will cut fares when decrease in CNG prices will be made', 'HONG KONG  Asian markets started      on an upswing in limited trading on Friday  with mainland Chinese stocks surging in Hong Kong on speculation Beijing may ease monetary policy to boost slowing growth Hong Kong

get articles
tokenize articles
lem - remove punc - etc
turn into frequency - like in assignment 3
use tfid vectorizer
get tf-idf matrix
get pairwise euclidian distance matrix
get pairwise cos similarity matrix



In [30]:
corpus = []
df = pd.DataFrame(data)

